// Picks random points centered on real cities (population >= 100,000).
// City list is generated by scripts/build-cities.js from GeoNames cities15000.
// Each pick is jittered within ~3 km so repeated rounds vary streets/neighborhoods.

const fs = require('fs');
const path = require('path');

const JITTER_KM = 3;

const CITIES = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'cities.json'), 'utf8')
);

// Uniform random point within a disk of given km radius around (lat, lng).
function jitter(lat, lng, maxKm) {
  const r = Math.sqrt(Math.random()) * maxKm; // sqrt => uniform over area
  const theta = Math.random() * 2 * Math.PI;
  const dLatKm = r * Math.cos(theta);
  const dLngKm = r * Math.sin(theta);
  const dLat = dLatKm / 111;
  const cosLat = Math.cos(lat * Math.PI / 180);
  const dLng = dLngKm / (111 * (cosLat || 1e-6));
  return {
    lat: parseFloat((lat + dLat).toFixed(4)),
    lng: parseFloat((lng + dLng).toFixed(4)),
  };
}

// Pick a random city (equal weight), then a jittered point around it.
function generateRandomPoint() {
  const city = CITIES[Math.floor(Math.random() * CITIES.length)];
  return jitter(city.lat, city.lng, JITTER_KM);
}

module.exports = { generateRandomPoint };
